# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: steammessages_site_license.steamclient.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from steammessages_unified_base import steamclient_pb2 as steammessages__unified__base_dot_steamclient__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='steammessages_site_license.steamclient.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n,steammessages_site_license.steamclient.proto\x1a,steammessages_unified_base.steamclient.proto\"P\n/CSiteLicense_ClientSiteAssociation_Notification\x12\x1d\n\x15site_association_file\x18\x01 \x01(\x0c\x32\xb0\x01\n\x0bSiteLicense\x12\x86\x01\n\x15\x43lientSiteAssociation\x12\x30.CSiteLicense_ClientSiteAssociation_Notification\x1a\x0b.NoResponse\".\x82\xb5\x18*Client is sending up site association info\x1a\x18\x82\xb5\x18\x14Site License serviceB\x03\x80\x01\x01')
  ,
  dependencies=[steammessages__unified__base_dot_steamclient__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CSITELICENSE_CLIENTSITEASSOCIATION_NOTIFICATION = _descriptor.Descriptor(
  name='CSiteLicense_ClientSiteAssociation_Notification',
  full_name='CSiteLicense_ClientSiteAssociation_Notification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='site_association_file', full_name='CSiteLicense_ClientSiteAssociation_Notification.site_association_file', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=174,
)

DESCRIPTOR.message_types_by_name['CSiteLicense_ClientSiteAssociation_Notification'] = _CSITELICENSE_CLIENTSITEASSOCIATION_NOTIFICATION

CSiteLicense_ClientSiteAssociation_Notification = _reflection.GeneratedProtocolMessageType('CSiteLicense_ClientSiteAssociation_Notification', (_message.Message,), dict(
  DESCRIPTOR = _CSITELICENSE_CLIENTSITEASSOCIATION_NOTIFICATION,
  __module__ = 'steammessages_site_license.steamclient_pb2'
  # @@protoc_insertion_point(class_scope:CSiteLicense_ClientSiteAssociation_Notification)
  ))
_sym_db.RegisterMessage(CSiteLicense_ClientSiteAssociation_Notification)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\200\001\001'))
# @@protoc_insertion_point(module_scope)
